In [7]:
import numpy as np
a=np.array([[1,3],[4,5]])

In [8]:
a.ndim

2

In [9]:
a

array([[1, 3],
       [4, 5]])

In [10]:
a.shape

(2, 2)

In [13]:
a.max()

5

In [14]:
a.min()

1

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.randn(5)

array([-1.19478273,  0.17555401,  0.87581068, -1.75508872, -0.12358186])

In [36]:
np.random.randn(3,4)

array([[ 0.0496196 , -0.18886975,  0.28508046, -0.31137156],
       [ 0.04319895,  0.8064708 ,  1.38920441,  0.44637115],
       [-1.62570317,  1.14732355, -0.27159909, -0.81296357]])

In [46]:
np.random.randint(5,150,5)

array([131, 110,  71,  74, 107])

# arange,linespace

In [47]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
np.arange(3,20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [54]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [55]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
a

array([[1, 3],
       [4, 5]])

In [62]:
type(a)

numpy.ndarray

In [64]:
print(a.ndim)

2


In [65]:
a.min()

1

In [66]:
a.max()

5

In [69]:
a

array([[1, 3],
       [4, 5]])

In [71]:
a.shape

(2, 2)

# reshape function

In [73]:
a=np.array([[1,2],[3,4],[5,6]])

In [74]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
a.shape

(3, 2)

In [77]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [79]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [81]:
a.dtype

dtype('int32')